server:
  port: 8080

spring:
  application:
    name: minigame-service
    
  # ⭐ DataSource 설정 추가 (핵심 수정)
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:${MYSQL_PORT:3306}/middle_point_service_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:middle_point_user}
    password: ${MYSQL_PASSWORD:middle_point_password}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never  # data.sql 비활성화 (PenaltySeeder로 대체)
      encoding: UTF-8
      continue-on-error: true

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# 로깅 설정
logging:
  level:
    root: INFO
    su.kdt.minigame: DEBUG
