server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: minigame-service
    
  # ⭐ DataSource 설정 추가 (핵심 수정)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:${MYSQL_PORT:3306}/beetween_us_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Root123!}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Flyway 설정 (JPA 순환 참조 방지)
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration
    
  sql:
    init:
      mode: never  # Flyway 사용으로 변경
      encoding: UTF-8
      continue-on-error: true

  # Jackson 설정 (LocalDateTime 직렬화)
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss

  # SSE/Async 설정 추가 (타임아웃 문제 해결)
  mvc:
    async:
      request-timeout: 600000 # 10분 (기본 30초에서 늘림)

  # HTTP 인코딩 설정 (한글 깨짐 방지)
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# 로깅 설정
logging:
  level:
    root: INFO
    su.kdt.minigame: DEBUG
