spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13307/middle_point_service_db?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: middle_point_user
    password: middle_point_password
