spring:
  config:
    activate:
      on-profile: ci

  datasource:
    url: jdbc:mysql://host.docker.internal:3307/minigame_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: minigame_user
    password: minigame_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: host.docker.internal
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms

logging:
  level:
    org.hibernate.SQL: WARN
    su.kdt.minigame: INFO
    org.flywaydb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info