spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/middle_point_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: middle_point_user
    password: middle_point_password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: redis
      port: 6379

  h2:
    console:
      enabled: false
  
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
